import type { Locale } from "./types";

export const growthPath = "/growth/90-day-social-media-growth-system";
export type GrowthReview = { period: "month-1" | "month-2" | "month-3" | "final-90-day"; verified: true; summary: string; metrics: { label: string; value: string }[] };
// Add a review only after its actual performance data has been verified.
export const growthReviews: Record<Locale, GrowthReview[]> = { en: [], ar: [] };

const en = {
  title: "90-Day Social Media Growth & Lead Generation System",
  description: "A designed and handed-off commercial growth system connecting social-media strategy, qualification and sales-pipeline measurement. Performance results pending measurement.",
  label: "SUPPORTING GROWTH CASE", company: "Innovation for Solar Systems", back: "Back to Portfolio", contact: "Discuss Growth & Business Development",
  summary: "Designed a 90-day growth system intended to connect social-media activity with measurable commercial actions rather than vanity metrics alone.",
  challengeHeading: "Commercial Challenge", challenge: "Move the company's social-media presence from a mainly informational channel toward a measurable commercial growth channel. The intended journey connects qualified interest with WhatsApp, qualification, site visits, proposals and contracts; these are designed stages, not achieved results.",
  roleHeading: "Ahmed's Role", role: "Strategy Owner / Growth & Business Development",
  responsibilities: ["Growth strategy and target-segment prioritization", "Content architecture, lead-generation offers and CTA system", "Commercial funnel and qualification logic", "Production workflow and team execution handoff", "KPI, testing and weekly review frameworks"],
  scaleHeading: "System Scale", scale: [{ value: "15", label: "Execution Worksheets" }, { value: "90 Days", label: "Commercial Growth Plan" }, { value: "67", label: "Planned Content Pieces" }, { value: "40", label: "Planned Reels" }, { value: "14", label: "Planned Customer-Proof Pieces" }],
  sheetsHeading: "Inside the execution workbook", sheets: ["Dashboard", "90-Day Calendar", "Strategy", "Weekly System", "Reels Plan", "Stories", "Customer Proof", "Offers & CTA", "Production Workflow", "Repurposing", "KPI Tracker", "Testing", "Top 15 Ideas", "First 14 Days", "Lookups"],
  funnelHeading: "From Attention to Commercial Intent", funnelNote: "Designed funnel architecture. Performance at each stage remains to be measured.", attentionLabel: "Growth funnel", attention: ["Attention", "Trust", "Authority", "Proof", "Conversion"], commercialLabel: "Commercial journey", commercial: ["Content", "WhatsApp", "Qualification", "Site Visit", "Proposal", "Contract"],
  segmentsHeading: "Segment Strategy", segments: [{ label: "PRIMARY", title: "Farms / Irrigation / Pumps" }, { label: "SECONDARY", title: "Factories / Commercial Facilities" }, { label: "B2B", title: "Solar Companies / Contractors / Partnerships" }, { label: "SUPPORTING", title: "Residential opportunities when relevant" }], segmentNote: "Prioritize segment-specific problems, offers, CTAs and qualification inputs rather than a single generic message.",
  architectureHeading: "Content + Offer Architecture", pillarsHeading: "Commercial content functions", pillars: ["Customer Proof / Case Studies", "Engineering Authority", "Agriculture & Irrigation Problems", "ROI / Cost Education", "Project Quality / BTS", "FAQ / Objection Handling", "Factory / Commercial", "After-Sales", "B2B Partnerships", "Offers"],
  offersHeading: "Content → Specific CTA → Qualification Input", offers: [{ segment: "Farm / Irrigation", offer: "Initial Irrigation Cost Analysis", input: "Pump HP, operating hours, location and basic application data" }, { segment: "Factory", offer: "Electricity Bill & Load Review", input: "Bill, activity and operating hours" }, { segment: "B2B", offer: "BOQ / Project Review", input: "BOQ, quantities and timeline / scope" }, { segment: "General", offer: "Initial Solar Assessment", input: "Initial application context" }],
  productionHeading: "Production Operating System", production: ["Idea Selection", "Script", "Shoot", "Edit", "Technical Validation", "Approval", "Publish", "Respond & Qualify", "Measure", "Repurpose"], productionNote: "Each stage assigns an owner, input, action, output, SLA / deadline and completion rule.",
  validationHeading: "Technical Validation & Claim Control", validation: "Savings claims, ROI figures, technical numbers and performance claims require technical validation before publishing. Customer proof must use verified facts and customer permission when appropriate.",
  leadHeading: "Marketing-to-Sales Alignment", lead: ["Public Comment / Message", "Messenger / WhatsApp", "Qualification", "Next Action", "CRM / Sales Follow-Up"], leadNote: "Intent signals include price, details, number of panels, pump suitability, location and project questions. The designed response moves interest toward a qualified next action.",
  kpiHeading: "KPI Framework", kpiNote: "Three measurement layers, with efficiency tracked across them. Designed to optimize for qualified commercial intent; no measured results are presented.", kpis: [{ title: "Marketing Signals", metrics: "Reach · Video Views · Retention · Shares · Saves · Profile Visits" }, { title: "Commercial Intent", metrics: "WhatsApp Clicks · Leads · Qualified Leads · Site Visits" }, { title: "Pipeline", metrics: "Proposals · Contracts" }, { title: "Efficiency", metrics: "Ad Spend · CPL · CPQL" }],
  testingHeading: "Experimentation", testingRule: "ONE VARIABLE AT A TIME", testingVariables: "Hook · Offer · CTA · Segment · Format", testing: ["Test", "Measure", "Select Winner", "Scale Winner", "Stop Repeating Losers"], testingNote: "The tracker represents test design. No winning test or performance improvement is claimed.",
  handoffHeading: "Team Handoff & Governance", handoff: "Strategy developed, execution system built and plan delivered to the social-media execution team. Team handoff completed; performance results pending measurement.",
  sprintHeading: "Launch Sprint Design — Days 1–14", sprint: "Positioning / CTA setup, WhatsApp qualification responses, customer-proof preparation, engineer Reel batch production, initial publishing, irrigation lead offer, BTS / project footage and the first performance review were designed into the launch sprint. Completion of these launch activities is not claimed.",
  proofHeading: "Reusable Customer Proof", proof: "One customer visit can feed a testimonial, Reels, a case study, a quote, Stories, BTS, WhatsApp proof and ad creative. This is a designed repurposing system, not a claim that those assets have been produced.",
  reviewHeading: "Weekly Performance Review + Month-End Growth Review", review: "Review logic evaluates the strongest segment, hook, CTA and content, qualification quality, lead-loss reasons and the next execution decision.",
  statusHeading: "Current Status", statuses: [{ label: "Strategy", value: "Completed" }, { label: "Execution System", value: "Completed" }, { label: "Team Handoff", value: "Completed" }, { label: "Live Results", value: "Pending measurement" }],
  resultsHeading: "Verified Performance Reviews", supportingTitle: "90-Day Social Media Growth & Lead Generation System", supportingDescription: "Designed and handed off a 90-day commercial social-media system connecting content strategy, qualification, WhatsApp conversations and sales-pipeline measurement.", supportingStatus: "Strategy, execution system and team handoff completed. Performance results pending measurement.", chips: ["90 Days", "15-Sheet System", "67 Planned Pieces", "Lead Funnel + KPI Framework"], cta: "View Growth System",
};

const ar: typeof en = {
  title: "نظام نمو وتوليد فرص مبيعات عبر السوشيال ميديا لمدة 90 يومًا",
  description: "نظام نمو تجاري تم تصميمه وتسليمه لفريق التنفيذ، يربط استراتيجية السوشيال ميديا بالتأهيل وقياس مسار المبيعات. النتائج الفعلية قيد القياس.",
  label: "حالة نمو داعمة", company: "Innovation for Solar Systems", back: "العودة إلى الأعمال", contact: "لنتحدث عن النمو وتطوير الأعمال",
  summary: "تصميم نظام نمو لمدة 90 يومًا يهدف إلى ربط نشاط السوشيال ميديا بخطوات تجارية قابلة للقياس، بدلًا من الاكتفاء بمؤشرات التفاعل العامة.",
  challengeHeading: "التحدي التجاري", challenge: "نقل حضور الشركة على السوشيال ميديا من قناة معلوماتية في الأساس إلى قناة نمو تجاري قابلة للقياس. يربط المسار المصمم الاهتمام المؤهل بمحادثات WhatsApp والتأهيل والمعاينة والعرض والتعاقد؛ وهذه مراحل مخططة وليست نتائج محققة.",
  roleHeading: "دوري في المشروع", role: "مسؤول الاستراتيجية / النمو وتطوير الأعمال",
  responsibilities: ["تصميم استراتيجية النمو وترتيب أولويات الشرائح المستهدفة", "بناء هيكل المحتوى وعروض توليد الفرص ونظام CTA", "تصميم مسار المبيعات ومنطق التأهيل", "تصميم سير الإنتاج وتسليم النظام لفريق التنفيذ", "بناء أطر KPI والاختبار والمراجعة الأسبوعية"],
  scaleHeading: "حجم النظام", scale: [{ value: "15", label: "ورقة عمل تنفيذية" }, { value: "90 يومًا", label: "خطة نمو تجاري" }, { value: "67", label: "قطعة محتوى مخططة" }, { value: "40", label: "مقطع Reels مخططًا" }, { value: "14", label: "محتوى إثبات من العملاء مخططًا" }],
  sheetsHeading: "داخل ملف التنفيذ", sheets: ["لوحة المتابعة", "تقويم 90 يومًا", "الاستراتيجية", "النظام الأسبوعي", "خطة Reels", "Stories", "إثبات العملاء", "العروض وCTA", "سير الإنتاج", "إعادة توظيف المحتوى", "متابعة KPI", "الاختبارات", "أفضل 15 فكرة", "أول 14 يومًا", "القوائم المرجعية"],
  funnelHeading: "من الانتباه إلى الاهتمام التجاري", funnelNote: "هيكل مصمم لمسار النمو والمبيعات؛ أداء كل مرحلة لم يُقَس بعد.", attentionLabel: "مسار النمو", attention: ["الانتباه", "الثقة", "المرجعية", "الإثبات", "التحويل"], commercialLabel: "المسار التجاري", commercial: ["المحتوى", "WhatsApp", "التأهيل", "المعاينة", "العرض", "التعاقد"],
  segmentsHeading: "استراتيجية الشرائح", segments: [{ label: "الأولوية الأولى", title: "المزارع / الري / الطلمبات" }, { label: "الأولوية الثانية", title: "المصانع / المنشآت التجارية" }, { label: "B2B", title: "شركات الطاقة الشمسية / المقاولون / الشراكات" }, { label: "داعم", title: "الفرص السكنية عند ملاءمتها" }], segmentNote: "ربط مشكلات كل شريحة بالعرض المناسب وCTA ومدخلات التأهيل، بدلًا من رسالة عامة واحدة.",
  architectureHeading: "هيكل المحتوى والعروض", pillarsHeading: "وظائف المحتوى التجارية", pillars: ["إثبات العملاء / دراسات الحالات", "المرجعية الهندسية", "مشكلات الزراعة والري", "التوعية بالتكلفة وROI", "جودة المشاريع / BTS", "الأسئلة والاعتراضات", "المصانع / المنشآت التجارية", "ما بعد البيع", "شراكات B2B", "العروض"],
  offersHeading: "محتوى ← CTA محدد ← مدخلات التأهيل", offers: [{ segment: "المزارع / الري", offer: "تحليل أولي لتكلفة الري", input: "قدرة الطلمبة HP وساعات التشغيل والموقع وبيانات الاستخدام الأساسية" }, { segment: "المصانع", offer: "مراجعة فاتورة الكهرباء والأحمال", input: "الفاتورة وطبيعة النشاط وساعات التشغيل" }, { segment: "B2B", offer: "مراجعة BOQ / المشروع", input: "BOQ والكميات والجدول الزمني / النطاق" }, { segment: "عام", offer: "تقييم أولي للطاقة الشمسية", input: "السياق الأولي للاستخدام" }],
  productionHeading: "نظام تشغيل الإنتاج", production: ["اختيار الفكرة", "السيناريو", "التصوير", "المونتاج", "التحقق الفني", "الاعتماد", "النشر", "الرد والتأهيل", "القياس", "إعادة التوظيف"], productionNote: "لكل مرحلة مسؤول ومدخل وإجراء ومخرج وSLA / موعد تسليم وقاعدة واضحة للاكتمال.",
  validationHeading: "التحقق الفني وضبط الادعاءات", validation: "تتطلب ادعاءات التوفير وأرقام ROI والأرقام الفنية وادعاءات الأداء تحققًا فنيًا قبل النشر. يعتمد إثبات العملاء على حقائق موثقة وموافقة العميل عند الحاجة.",
  leadHeading: "الربط بين التسويق والمبيعات", lead: ["تعليق / رسالة عامة", "Messenger / WhatsApp", "التأهيل", "الخطوة التالية", "CRM / متابعة المبيعات"], leadNote: "تشمل إشارات الاهتمام السعر والتفاصيل وعدد الألواح وملاءمة الطلمبة والموقع والسؤال عن مشروع. يوجه مسار الرد المصمم هذا الاهتمام نحو خطوة تالية مؤهلة.",
  kpiHeading: "إطار KPI", kpiNote: "ثلاث طبقات قياس مع متابعة الكفاءة عبرها. الهدف هو الاهتمام التجاري المؤهل؛ لا تُعرض نتائج أداء فعلية.", kpis: [{ title: "إشارات التسويق", metrics: "الوصول · مشاهدات الفيديو · الاحتفاظ بالمشاهدة · المشاركات · الحفظ · زيارات الملف" }, { title: "الاهتمام التجاري", metrics: "نقرات WhatsApp · الفرص · الفرص المؤهلة · المعاينات" }, { title: "مسار المبيعات", metrics: "العروض · التعاقدات" }, { title: "الكفاءة", metrics: "الإنفاق الإعلاني · CPL · CPQL" }],
  testingHeading: "التجريب", testingRule: "متغير واحد في كل اختبار", testingVariables: "الافتتاحية · العرض · CTA · الشريحة · الشكل", testing: ["اختبار", "قياس", "اختيار الأفضل", "توسيع الأفضل", "إيقاف تكرار غير الفعال"], testingNote: "يمثل سجل الاختبارات تصميم النظام؛ لا يُنسب إليه اختبار فائز أو تحسن في الأداء بعد.",
  handoffHeading: "تسليم الفريق وحوكمة التنفيذ", handoff: "تم تطوير الاستراتيجية وبناء نظام التنفيذ وتسليم الخطة لفريق السوشيال ميديا. تسليم النظام مكتمل، والنتائج الفعلية قيد القياس.",
  sprintHeading: "تصميم مرحلة الإطلاق — الأيام 1–14", sprint: "تتضمن خطة الإطلاق ضبط التموضع وCTA، وردود تأهيل WhatsApp، وتجهيز إثبات العملاء، وإنتاج دفعة Reels هندسية، والنشر الأولي، وعرض الري، ولقطات BTS / المشاريع، وأول مراجعة للأداء. لا يُدّعى اكتمال هذه الأنشطة.",
  proofHeading: "إثبات العملاء القابل لإعادة الاستخدام", proof: "يمكن أن تغذي زيارة عميل واحدة شهادة عميل وReels ودراسة حالة واقتباسًا وStories وBTS وإثباتًا عبر WhatsApp ومادة إعلانية. هذا نظام مصمم لإعادة التوظيف، وليس ادعاءً بإنتاج هذه المواد بالفعل.",
  reviewHeading: "مراجعة أداء أسبوعية ومراجعة نمو بنهاية الشهر", review: "تقيّم المراجعة أقوى شريحة وافتتاحية وCTA ومحتوى، وجودة التأهيل وأسباب فقد الفرص وقرار التنفيذ التالي.",
  statusHeading: "الحالة الحالية", statuses: [{ label: "الاستراتيجية", value: "مكتملة" }, { label: "نظام التنفيذ", value: "مكتمل" }, { label: "تسليم الخطة لفريق التنفيذ", value: "مكتمل" }, { label: "النتائج الفعلية", value: "قيد القياس" }],
  resultsHeading: "مراجعات الأداء الموثقة", supportingTitle: "نظام نمو وتوليد فرص مبيعات عبر السوشيال ميديا – 90 يومًا", supportingDescription: "تصميم وتسليم نظام نمو للسوشيال ميديا لمدة 90 يومًا يربط استراتيجية المحتوى بالتأهيل ومحادثات WhatsApp وقياس مسار المبيعات.", supportingStatus: "الاستراتيجية ونظام التنفيذ وتسليم الفريق مكتملة؛ النتائج الفعلية قيد القياس.", chips: ["90 يومًا", "نظام من 15 ورقة", "67 قطعة مخططة", "مسار الفرص + إطار KPI"], cta: "استعرض نظام النمو",
};
export const getGrowthCase = (locale: Locale) => locale === "ar" ? ar : en;
